<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <style>
        .errors {
            display: none;
            color: darkred;
        }

        .form-element-wrapper {
            margin: 1em;
        }
    </style>
</head>
<body>

<h1>Hello World!</h1>

<h3>Registration form for the Star Event</h3>

<form id="event-registration" action="/submit-form" method="post">

    <div class="form-element-wrapper">
        <label for="name">Full Name*:</label>
        <br>
        <input type="text" id="name" name="name" value="<?php echo htmlspecialchars($name) ?>">

        <ul id="name-messages" class="errors"></ul>
    </div>

    <div class="form-element-wrapper">
        <label for="email">Your email address*:</label>
        <br>
        <input type="text" id="email" name="email">
        <ul id="email-messages" class="errors"></ul>
    </div>

    <div class="form-element-wrapper">
        <label>Select Town*:
            <select name="town" id="town-list-element">
                <option value="0">Select...</option>
                <?php foreach ($townsList as $town): ?>
                    <option value="<?php echo $town->getId() ?>"><?php echo $town->getTown() ?></option>
                <?php endforeach; ?>
            </select>
        </label>

        <ul id="town-messages" class="errors"></ul>

        <script>
            $(document).ready(function () {
                $("#town-list-element").change(function () {
                    $.ajax({
                        url: "/event-sessions",
                        method: 'post',
                        data: JSON.stringify({selectedTown: $(this).val()}),
                        contentType: "application/json; charset=utf-8",
                        dataType: "json",
                        success: function (response) {
                            $('#no-any-event-session-message').hide();
                            const events = JSON.parse(JSON.stringify(response));
                            $('#events-list > option').remove();
                            $('#events-list').append($('<option></option>').text('Select...'));
                            if (events.length) {
                                $.each(events, function (key, value) {
                                    $('#events-list')
                                        .append($("<option></option>")
                                            .attr("value", value.dt)
                                            .text(value.label));
                                });
                                //$('#event-session-element').show();
                            } else {
                                $('#no-any-event-session-message').show();
                            }
                        },
                        error: function (response) {
                            console.log(response);
                        }
                    });
                });
            });
        </script>
    </div>

    <div class="form-element-wrapper">
        <label id="event-session-element">Set Date and time*:
            <select name="event-session" id="events-list">
                <option value="0">Select...</option>
            </select>
        </label>

        <ul id="event-session-messages" class="errors"></ul>

        <p id="no-any-event-session-message" style="display: none">
            <em>No any session at next week</em>
        </p>
    </div>

    <div class="form-element-wrapper">
        <label for="comment">Your comment:
            <br>
            <textarea rows="10" cols="45" name="comment" id="comment"></textarea>
        </label>
        <ul id="comment-messages" class="errors"></ul>
    </div>

    <input type="hidden" name="csrf_token" value="<?php echo $csrf ?>">
    <input type="submit" value="Send">

</form>

<script>
    $(document).ready(function () {

        $('form#event-registration').submit(function (event) {
            event.preventDefault();
            sendForm(1);
        });

        $('input[name="name"], input[name="email"]').change(function (event) {
            sendForm(0);
        });

        $('select[name="town"]').change(function (event) {
            $('select[name="event-session"]').val(0);
        });

        $('select[name="town"], select[name="event-session"]').change(function (event) {
            sendForm(0);
        });

        const sendForm = function (submit) {
            const form = $('form#event-registration');
            const formData = new FormData();
            formData.append('csrf_token', form.find('input[name="csrf_token"]').val());
            formData.append('name', form.find('input[name="name"]').val());
            formData.append('email', form.find('input[name="email"]').val());
            formData.append('town', form.find('select[name="town"]').val());
            formData.append('event-session', form.find('select[name="event-session"]').val());
            formData.append('comment', form.find('textarea[name="comment"]').val());
            formData.append('submit', submit);
            $.ajax({
                url: form.attr('action'),
                method: form.attr('method'),
                data: formData,
                processData: false,
                contentType: false,
                success: function (response) {
                    const data = JSON.parse(JSON.stringify(response));
                    if (data.hasOwnProperty('status') && data.status === 'done') {
                        document.location.href = '/done'
                    }
                    $('.form-element-wrapper > .errors > li').remove();
                    $('.form-element-wrapper > .errors').hide();
                    $.each(data, function (key, errors) {
                        $.each(errors, function (id, error) {
                            $('ul#' + key + '-messages').append($('<li></li>').text(error));
                        });
                        $('.form-element-wrapper > .errors').show();
                    });
                },
                error: function (response) {
                    console.log(response);
                }
            });
        }
    });
</script>

</body>
</html>
